trip_data_extractor:
  description: >
    extract the trip details from the input prompt {input_details} given by the user.
  expected_output: >
    detailed output of the time period in sri lanka,
    the locations where the user wants to go,
    prefferes hotels / lodges, meal preferences,
    Total budget,

find_best_path:
  description: >
    Find the best path for the trip based on the cities the user mentioned.
    calculate the expected travel time, distance, and cost(transport) for the trip.
  expected_output: >
    detailed output of the best path for the trip based on the cities the user mentioned.
    provide the distance, time, cost(transport) from the origin to the destination.